      Dim(1) = -((5.q-1*(-(1q0*(k1k3*k2k3 - k1k2*k3k3*1q0)*
     &           (k2k3*(C0ACD - C0BCD*1q0 - 
     &                D0m*1q0*(k1k1 + m1q - m2q*1q0)) + 
     &             k1k3*(C0BCD - C0ABD*1q0 + 
     &                D0m*(k2k2 + m1q - m3q*1q0)))) + 
     &        (k1k3*k2k2 - k1k2*k2k3*1q0)*
     &         (k3k3*(C0ACD - C0BCD*1q0 - 
     &              D0m*1q0*(k1k1 + m1q - m2q*1q0)) + 
     &           k1k3*(C0BCD - C0ABC*1q0 + 
     &              D0m*(k3k3 + m1q - m4q*1q0)))))/
     &    (k1k3*(k1k3**2*k2k2 + k1k2**2*k3k3 + 
     &        k1k1*(k2k3**2 - k2k2*k3k3*1q0) - 
     &        k1k2*k1k3*k2k3*2q0)))
        Dim(2) = (5.q-1*(C0ABD*k1k3**2 + D0m*k1k1*k1k3*k2k3 + 
     &      C0ACD*k1k2*k3k3 + D0m*k1k2*k1k3*k3k3 + 
     &      D0m*k1k1*k2k2*k3k3 + D0m*k1k2*k1k3*m1q + 
     &      D0m*k1k3*k2k3*m1q + D0m*k1k1*k3k3*m1q + 
     &      D0m*k1k2*k3k3*m2q + D0m*k1k3**2*m3q + 
     &      D0m*k1k1*k2k3*m4q - D0m*k1k3**2*k2k2*1q0 - 
     &      C0ACD*k1k3*k2k3*1q0 - C0ABD*k1k1*k3k3*1q0 - 
     &      D0m*k1k1*k1k2*k3k3*1q0 - D0m*k1k1*k2k3*k3k3*1q0 - 
     &      D0m*k1k3**2*m1q*1q0 - D0m*k1k1*k2k3*m1q*1q0 - 
     &      D0m*k1k2*k3k3*m1q*1q0 - D0m*k1k3*k2k3*m2q*1q0 - 
     &      D0m*k1k1*k3k3*m3q*1q0 - D0m*k1k2*k1k3*m4q*1q0 + 
     &      C0ABC*(k1k1*k2k3 - k1k2*k1k3*1q0) + 
     &      C0BCD*(-(k1k2*k3k3*1q0) + 
     &         k1k3*(k1k2 + k2k3 - k1k3*1q0) + 
     &         k1k1*(k3k3 - k2k3*1q0))))/
     &  (k1k3**2*k2k2 + k1k2**2*k3k3 + 
     &    k1k1*(k2k3**2 - k2k2*k3k3*1q0) - k1k2*k1k3*k2k3*2q0)
        Dim(3) = -((5.q-1*(C0ABD*k1k2*k1k3 + D0m*k1k1*k1k3*k2k2 + 
     &        C0ACD*k1k2*k2k3 + D0m*k1k1*k2k2*k2k3 + 
     &        D0m*k1k2**2*k3k3 + D0m*k1k2**2*m1q + 
     &        D0m*k1k3*k2k2*m1q + D0m*k1k1*k2k3*m1q + 
     &        D0m*k1k2*k2k3*m2q + D0m*k1k2*k1k3*m3q + 
     &        D0m*k1k1*k2k2*m4q - C0ACD*k1k3*k2k2*1q0 - 
     &        D0m*k1k2*k1k3*k2k2*1q0 - C0ABD*k1k1*k2k3*1q0 - 
     &        D0m*k1k1*k1k2*k2k3*1q0 - D0m*k1k1*k2k2*k3k3*1q0 - 
     &        D0m*k1k2*k1k3*m1q*1q0 - D0m*k1k1*k2k2*m1q*1q0 - 
     &        D0m*k1k2*k2k3*m1q*1q0 - D0m*k1k3*k2k2*m2q*1q0 - 
     &        D0m*k1k1*k2k3*m3q*1q0 - D0m*k1k2**2*m4q*1q0 + 
     &        C0ABC*(k1k1*k2k2 - k1k2**2*1q0) + 
     &        C0BCD*(k1k2**2 + k1k3*k2k2 + k1k1*k2k3 - 
     &           k1k1*k2k2*1q0 - k1k2*(k1k3 + k2k3)*1q0)))/
     &    (k1k3**2*k2k2 + k1k2**2*k3k3 + 
     &      k1k1*(k2k3**2 - k2k2*k3k3*1q0) - 
     &      k1k2*k1k3*k2k3*2q0))
